import type { Metadata } from "next";
import { Nav } from "@/components/marketing/Nav";
import { Footer } from "@/components/marketing/Footer";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms governing your use of Learnzo."
};

export default function TermsPage() {
  return (
    <>
      <Nav />
      <main className="container-x py-12 max-w-3xl">
        <h1 className="text-4xl font-bold">Terms of Service</h1>
        <p className="mt-3 text-sm text-slate-500">Last updated: 6 October 2026</p>
        <div className="mt-8 space-y-6 text-slate-700 leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-slate-900">1. Agreement</h2>
            <p className="mt-2">By using learnzo.online you agree to these Terms. For any question about these Terms, contact support@learnzo.online.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900">2. What Learnzo provides</h2>
            <p className="mt-2">Learnzo is an AI homework help platform that accepts typed questions, photos of homework, and PDFs, and generates explanations, practice questions, and printable worksheets. It is a learning aid, not a substitute for school, teachers, or tutors.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900">3. Accounts</h2>
            <p className="mt-2">You are responsible for keeping your password confidential. If you are under 18, a parent or legal guardian must agree to these terms on your behalf.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900">4. Acceptable use</h2>
            <p className="mt-2">Do not upload illegal or harmful content, scrape or abuse the service, resell outputs, interfere with security, or upload another person's private data. We may suspend accounts that violate these rules.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900">5. Use by parents and students</h2>
            <p className="mt-2">Learnzo is designed to support learning. Use it to understand homework, not to copy answers.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900">6. Plans and pricing</h2>
            <p className="mt-2">Learnzo offers a free plan and paid plans. Paid plans are one-time purchases valid for the stated duration (monthly or yearly). Current pricing is on our Pricing page. Prices are in INR, inclusive of applicable taxes.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900">7. Payments</h2>
            <p className="mt-2">Payments are processed by Razorpay. We do not store card or UPI details. Plans are one-time purchases valid for their stated duration. There is no automatic renewal and no recurring subscription. Refunds are only issued as described in our Refund Policy.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900">8. AI-generated content</h2>
            <p className="mt-2">Explanations are generated by AI and can occasionally contain errors. We do not guarantee that any explanation is error-free or that it will result in any specific academic outcome.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900">9. Intellectual property</h2>
            <p className="mt-2">You own the content you upload. We own the Learnzo brand, design and code.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900">10. Availability</h2>
            <p className="mt-2">We do not guarantee uninterrupted service. Maintenance and third-party outages can occur.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900">11. Limitation of liability</h2>
            <p className="mt-2">To the maximum extent permitted by law, our total liability for any claim is limited to the amount you paid us in the last 12 months.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900">12. Changes</h2>
            <p className="mt-2">We may update these Terms. The Last updated date at the top will change.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900">13. Governing law</h2>
            <p className="mt-2">These Terms are governed by the laws of India. Disputes are subject to the exclusive jurisdiction of the courts in Karnataka, India.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-slate-900">14. Contact</h2>
            <p className="mt-2">Email support@learnzo.online.</p>
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}